/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tadkp;

import javax.swing.JOptionPane;

/**
 *
 * @author wahyu
 */
public class design extends javax.swing.JFrame {
    

    /**
     * Creates new form design
     */
    public design() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        date = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        time = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lapangan = new javax.swing.JComboBox<>();
        hasil = new javax.swing.JTextField();
        pesan = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        waktumulai = new javax.swing.JComboBox<>();
        waktuselesai = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Booking Futsal");
        jLabel1.setMinimumSize(new java.awt.Dimension(70, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 210, 38));

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Nama Pemesan ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 83, -1, -1));

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Tanggal ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 128, 113, -1));

        name.setBackground(new java.awt.Color(255, 255, 51));
        name.setForeground(new java.awt.Color(0, 0, 0));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 80, 141, -1));

        date.setBackground(new java.awt.Color(255, 255, 51));
        date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 126, 64, -1));

        month.setBackground(new java.awt.Color(255, 255, 51));
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        jPanel1.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 126, 64, -1));

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Waktu Bermain");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 172, 160, -1));

        time.setBackground(new java.awt.Color(255, 255, 51));
        time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 170, 64, -1));

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("No Hp");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 257, 133, -1));

        number.setBackground(new java.awt.Color(255, 255, 51));
        number.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 254, 140, -1));

        jLabel7.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("Lapangan");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 210, 144, -1));

        lapangan.setBackground(new java.awt.Color(255, 255, 51));
        lapangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Lapangan 1", "Lapangan 2", "Lapangan 3", "Lapangan 4", " " }));
        lapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapanganActionPerformed(evt);
            }
        });
        jPanel1.add(lapangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 208, 140, -1));

        hasil.setBackground(new java.awt.Color(255, 255, 51));
        hasil.setForeground(new java.awt.Color(0, 0, 0));
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        jPanel1.add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 355, 140, -1));

        pesan.setText("Pesan");
        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });
        jPanel1.add(pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 355, 73, -1));

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel1.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 355, 73, -1));

        jLabel9.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 51));
        jLabel9.setText("Waktu Mulai");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 302, 133, -1));

        waktumulai.setBackground(new java.awt.Color(255, 255, 51));
        waktumulai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", " " }));
        waktumulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktumulaiActionPerformed(evt);
            }
        });
        jPanel1.add(waktumulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 300, 64, -1));
        waktumulai.getAccessibleContext().setAccessibleDescription("\n");

        waktuselesai.setBackground(new java.awt.Color(255, 255, 51));
        waktuselesai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", " " }));
        jPanel1.add(waktuselesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 64, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\wahyu\\Downloads\\wp2567605-futsal-wallpaper-background-hd.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, -160, 910, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void lapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lapanganActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
        // TODO add your handling code here:
        // Menambahkan perulangan untuk menampilkan harga per jam
    StringBuilder hargaPerJamStr = new StringBuilder("Harga per jam:\n");
    for (int i = 1; i <= 5; i++) {
        int jam = i;
        int harga = jam * 80000;
        hargaPerJamStr.append(jam).append(" jam: ").append(harga).append("\n");
    }
    JOptionPane.showMessageDialog(this, hargaPerJamStr.toString());
    int waktuTerpilih = Integer.parseInt(time.getSelectedItem().toString());
    int tagihan = waktuTerpilih * 80000;
    hasil.setText(String.valueOf(tagihan));
    
    String pesan = String.format("%s,\nTagihan yang harus dibayar adalah sebesar: %s", name.getText(), tagihan);
    JOptionPane.showMessageDialog(this, pesan);
        
        
        
        if (time.getSelectedItem() == "1"){
            int booking = 80000;
            hasil.setText("" + booking);
        } else if (time.getSelectedItem() == "2"){
            int booking = 2 * 80000;
            hasil.setText("" + booking);
        } else if (time.getSelectedItem() == "3"){
            int booking = 3 * 80000;
            hasil.setText("" + booking);
        } else if (time.getSelectedItem() == "4"){
            int booking = 4 * 80000;
            hasil.setText("" + booking);
        } else if (time.getSelectedItem() == "5"){
            int booking = 5 * 80000;
            hasil.setText("" + booking);
        } else {
            int booking = 6 * 80000;
            hasil.setText("" + booking);
        }
        JOptionPane.showMessageDialog(this, String.format(name.getText())+ "Terimakasih Telah Menggunakan layanan kami");
        
    }//GEN-LAST:event_pesanActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        name.setText("");
        date.setSelectedIndex(0);
        month.setSelectedIndex(0);
        time.setSelectedIndex(0);
        lapangan.setSelectedIndex(0);
        number.setText("");
        hasil.setText("");
        waktumulai.setSelectedIndex(0);
        waktuselesai.setSelectedIndex(0);
    }//GEN-LAST:event_batalActionPerformed

    private void waktumulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktumulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waktumulaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new design().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JComboBox<String> date;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> lapangan;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JButton pesan;
    private javax.swing.JComboBox<String> time;
    private javax.swing.JComboBox<String> waktumulai;
    private javax.swing.JComboBox<String> waktuselesai;
    // End of variables declaration//GEN-END:variables
}
